steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=settings.xml.encrypted
      - --plaintext-file=settings.xml
      - --location=global
      - --keyring=jiotty
      - --key=jiotty
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/jiotty/github.com/ylexus/jiotty:$SHORT_SHA', '--file', 'master.Dockerfile', '.' ]
images:
  - 'gcr.io/jiotty/github.com/ylexus/jiotty:$SHORT_SHA'